apiVersion: v1
kind: Pod
metadata:
  name: homework-pod
  namespace: homework
spec:
  initContainers:
  - name: init-container
    image: busybox
    command: ["sh", "-c", "mkdir -p /init && echo 'Hello, my name is Super Carrot' > /init/index.html"]
    volumeMounts:
    - name: homework-volume
      mountPath: /init
  containers:
  - name: web-server
    image: nginx:alpine
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: homework-volume
      mountPath: /homework
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "rm -f /homework/index.html"]
  volumes:
  - name: homework-volume
    emptyDir: {}
